import { NextResponse } from "next/server";
import { explainRequestSchema } from "@/lib/schema";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 45;

const SYSTEM_PROMPT = `You are the risk co-pilot inside Sentinel, a portfolio risk tool for leveraged crypto positions.

You are given a JSON risk report that has ALREADY been computed by the application's own engine. Your job is to explain and interrogate it, not to recompute it.

Rules:
- Every number you state must come from the supplied report. Never estimate, extrapolate, or invent a figure. If the report does not contain something, say so.
- Be direct about risk. If the numbers are bad, say they are bad and say which number says so.
- Prefer explaining the mechanism over restating the metric. "Your positions all move together in a sell-off, so the diversification you are counting on is not there when it matters" beats "stressed correlation is 0.87".
- Never tell the user to buy or sell a specific asset as investment advice. You may explain what the report's own prescribed actions would do to the report's own metrics, framed as what the model says, not as a recommendation.
- Keep answers under 200 words unless asked for detail.
- This is a risk model built on 90 days of history and a bootstrap simulation. Be honest about what it cannot see: unprecedented events, venue failure, depegs, and liquidity gaps are outside the model.`;

/**
 * Optional conversational layer over the deterministic narrator.
 *
 * The app is fully functional without an API key — the narrator in
 * lib/risk/narrate.ts covers the explanation path deterministically. This
 * endpoint only adds follow-up questions, and it degrades to a clear message
 * rather than a broken UI when no key is configured.
 */
export async function POST(request: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      {
        error: "not-configured",
        message:
          "The conversational co-pilot needs an ANTHROPIC_API_KEY. The written risk assessment above is generated by the deterministic narrator and does not require one.",
      },
      { status: 503 },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = explainRequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  }

  const { question, context } = parsed.data;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-5",
        max_tokens: 800,
        system: SYSTEM_PROMPT,
        messages: [
          {
            role: "user",
            content: `Risk report:\n\n${JSON.stringify(context, null, 1)}\n\nQuestion: ${
              question ?? "Walk me through the single most important risk in this book and why."
            }`,
          },
        ],
      }),
    });

    if (!res.ok) {
      const detail = await res.text();
      console.error("[explain] upstream error", res.status, detail);
      return NextResponse.json(
        { error: "The co-pilot is unavailable right now." },
        { status: 502 },
      );
    }

    const data = (await res.json()) as {
      content: { type: string; text?: string }[];
    };
    const text = data.content
      .filter((c) => c.type === "text")
      .map((c) => c.text ?? "")
      .join("\n")
      .trim();

    return NextResponse.json({ answer: text });
  } catch (error) {
    console.error("[explain] failed", error);
    return NextResponse.json(
      { error: "The co-pilot is unavailable right now." },
      { status: 502 },
    );
  }
}
